--SE AGREGARA UNA TABLA LLAMADA "Producto" DENTRO DE LA BASE DE DATOS LLAMADA "DB_VENTAS". LA BASE DE DATOS DB_VENTAS FUE 
--REALIZADA EN EL PRIMER EJERCICIO CUYO NOMBRE ES: "00 CREACION DE BASE DE DATOS UTILIZANDO ESQUEMAS - capitulo 3"
--EN LA BASE DE DATOS YA EXISTE UNA TABLA LLAMADA "Producto" EN EL ESQUEMA DE COMPRAS. PERO AUN ASI SE AGREGARA UNA TABLA QUE DE 
--IGUAL FORMA SE LLAMARA : Producto ,SOLO QUE SIN PERTENECER A NINGUNO DE LOS ESQUEMAS CREADOS EN ESE EJERCICIO.
--LA FINALIDAD ES REALIZAR LOS EJEMPLOS  CON UNA MAYOR CLARIDAD. ESTA TABLA PUEDE SER ELIMINADA DESPUES, PARA CONSERVAR LA 
--ESTRUCTURA DE LA BASE DE DATOS, PREVIAMENTE DEFINIDA.

use DB_VENTAS
go
create table Producto
(
Cod_Pro char(5) not null primary key,
Des_Pro varchar(50) not null,
Pre_Pro money not null,
Sac_Pro int not null,
Smi_Pro int not null,
Uni_Pro varchar(30) not null,
Lin_Pro varchar(30) not null,
Imp_Pro varchar(10) not null
)
go
