/*EN ESTE EJEMPLO SE VERA EL USO DE "BULK INSERT", ESTA SENTENCIA NOS SERVIRA PARA IMPORTAR DATOS HACIA UNA TABLA.
EN ESTE CASO SE LLENARA LA TABLA "COMPRAS.Producto" ES UNA TABLA QUE SE ENCUENTRA EN LA BASE DE DATOS "DB_VENTAS" QUE ES UNA BASE 
DE DATOS UTILIZANDO ESQUEMAS.ESTA BASE DE DATOS FUE EL PRIMER EJERCICIO DEL CAPITULO 3, EL SCRIPT LO ENCONTRARAS EN ESTE DIRECTORIO,
POR EL NOMBRE : 01CREACION DE BASE DE DATOS UTILIZANDO ESQUEMAS - capitulo 3

LA INSTRUCCION BULK INSERT, POSEE EL SIGUIENTE FORMATO:

BULK INSERT <Nombre_Tabla>
FROM 'ARCHIVO_DATOS'
WITH
(
FIELDTERMINATOR = <SIMBOLO_CAMPO_DETERMINADO>
FIRSTROW = <NUMERO_FILA>
ROWTERMINATOR = <SIMBOLO_FILA_TERMINADOR>
)
GO
*/
use
DB_VENTAS
go

bulk insert COMPRAS.Producto
from 'D:\PRODUCTOS.TXT'
WITH
(
FIELDTERMINATOR=',',
ROWTERMINATOR='\n',
FIRSTROW=1
)
GO
select * from COMPRAS.Producto
go